### PR TITLE
Implement Mylyn's org.eclipse.mylyn.tasks.bugs.support extension

### PR DESCRIPTION
**Pull request by Godin**

### CODE REVIEW

**Comment by Godin** [comment]
@marchof could you please review?

**Comment by marchof** [comment]
@Godin I would like to try/test this. Do you have a pointer which feature I need to install which consumes this extension point?

**Comment by Godin** [comment]
@marchof I suppose that plugin is `org.eclipse.mylyn.tasks.bugs` and included in feature `org.eclipse.mylyn.tasks.ide-feature`. When I run `org.eclipse.eclemma.ui` as Eclipse Application using "Running Platform" as active target platform in latest Eclipse Oxygen for Committers, then required feature is presented.

**Comment by marchof** [comment]
@Godin Ok, Oxygen did the trick. Works.

**Comment by Godin** [comment]
@marchof I think this is part of EPP for quite some time, at least should be in Neon too.

**Pull request merged**
