### PR TITLE
Move coverage session import/export to "Run/Debug" category

### PR DESCRIPTION
**Pull request by marchof**
Bug 507696

### CODE REVIEW

**Comment by marchof** [comment]
@Godin Replaces PR #3. Can you review please?

**Comment by Godin** [comment]
@marchof Marc, you know that was possible to push into the same branch and avoid creation of new PR? 😉 

To prevent worries: I'll have a look, just a bit later, need to clean other work queues.

**Comment by marchof** [comment]
@Godin This was also my understanding. I created a new PR as the old one didn't see the new (forced) push. Maybe this was a temporary GitHub problem.

Take your time. I will work on the reported UI issues step by step.

Should I send you individual notifications or should we rather use e.g. a tag "ready for review"?

**Comment by Godin** [comment]
@marchof on my side there is no reasons to change process - you can continue to use ping.
I just wanted to let you know that I'm alive 😉

**Comment by Godin** [comment]
@marchof here is my feedback

Seems that we have inconsistency in terminology:

`Export Session` in commit message, documentation and Coverage View:

coverage view

while `Coverage Report` in Export Dialog and Quick Access:

export dialog

quick access


Not sure that change of category in export really makes sense:
- seems naturally that coverage is next to export of Javadoc in Java category
- could be that our users used to this category over years, but this probably minor argument given that there is search in dialog

Icon in export dialog should have transparent background as others there - created https://bugs.eclipse.org/bugs/show_bug.cgi?id=507800

Also noticed that usage of Import/Export from Coverage View popup requires selection of category, what seems inconvenient, especially in case of change of category.

**Comment by Godin** [comment]
Also checked that we don't mention category in documentation, which is good - no change is required. However IMO mention in changelog is required (especially for user visible changes), but can be done later since anyway we expect some polishing of changelog due to move to Eclipse Foundation.

**Comment by marchof** [comment]
@Godin Thx, adjusted according to your comments.

**Comment by Godin** [comment]
@marchof in fact this was more of a question and I'm still wondering what is more natural for end-users:

1. to see "Report" in "Java" category

or

2. to see "Session" in "Run/Debug" category

I guess that not much people use export in JaCoCo format, and so mostly looking for generation of report.

Also let me check when this name appeared in a first time - maybe we renamed "session" into "report" in response to inability to find generation of report.

**Comment by Godin** [comment]
Word "report" was there since the inception of export ( https://github.com/jacoco/eclemma/commit/cb141eb68a459ac990a13f739aac4e1c9342f0ff ).

Also while documentation mostly uses "Session Export" there is at least one mention of "Coverage Report export wizard" that needs to be fixed, if we will decide to do this renaming:

documentation - import export

**Comment by Godin** [comment]
Regarding

> Also noticed that usage of Import/Export from Coverage View popup requires selection of category, what seems inconvenient, especially in case of change of category.

created https://bugs.eclipse.org/bugs/show_bug.cgi?id=507907

**Comment by marchof** [comment]
@Godin Fixed documentation.

**Comment by Godin** [comment]
@marchof ok, so even if this was not stated explicitly, I assume that you prefer consistent use of category "Run/Debug" and word "Session". At least I warned about possible user reaction :wink:

**Comment by Godin** [comment]
Ahh, and I missed comment https://bugs.eclipse.org/bugs/show_bug.cgi?id=507696#c3 :

> As EclEmma can also measure coverage for JVM languages other than Java, the Java category may actually be confusing for developers working with Scala, Xtend, or whatever.

which is a good argument.

**Comment by marchof** [comment]
@Godin Added test.

**Pull request merged**
