### PR TITLE
Add UI tests

### PR DESCRIPTION
**Pull request by Godin**

### CODE REVIEW

**Comment by Godin** [comment]
@marchof could you please review?

I think that this should be merged prior to #4 , so that change in #4 will come with proper update of test.
And I'll add test to #7 once this will be merged.

P.S. just in case - if you'll be doing merge, don't forget that we prefer linear history without merge commits. Or alternatively - I can merge after review.

**Comment by marchof** [comment]
@Godin I tried to execute on OS X and ended up with the following exception. Interestingly the situation does not change if I configure

    <useUIThread>true</useUIThread>

I'll investigate.

```
!ENTRY org.eclipse.osgi 4 0 2016-11-22 15:29:50.344
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4361)
	at org.eclipse.swt.SWT.error(SWT.java:4276)
	at org.eclipse.swt.SWT.error(SWT.java:4247)
	at org.eclipse.swt.widgets.Display.error(Display.java:1070)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:827)
	at org.eclipse.swt.widgets.Display.create(Display.java:810)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:130)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:701)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:692)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:669)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:161)
	at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:96)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:31)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:120)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:37)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
```

**Comment by Godin** [comment]
@marchof could you try `mvn clean verify -Dtycho.testArgLine=-XstartOnFirstThread` ?

**Comment by Godin** [comment]
@marchof could you please try `mvn clean verify -DskipUITests=false -Dtycho.testArgLine=-XstartOnFirstThread` ?

**Comment by marchof** [comment]
@Godin Works, nice!

**Comment by Godin** [comment]
@marchof ok, I also verified that this helps using OS X in Travis. I'll commit fix. Note that we don't run on OS X in Travis by default, because those executors are slow and busy usually.

BTW do you have same problem, when starting from Eclipse IDE and not from command-line using Tycho? I guess that inside IDE this parameter is added automatically, but confirmation will be nice.

**Comment by marchof** [comment]
@Godin I have a different issue with running the test directly in Eclipse. But I will sort out separately.

**Pull request merged**
