### PR TITLE
HiDPI icons

### PR DESCRIPTION
**Pull request by Godin**
Remove unused
- [x] `elcl16/collapseall.gif`
- [x] `elcl16/java_ovr.gif`

Use `org.eclipse.ui.ISharedImages` for
- [x] `elcl16/linked.gif`
- [x] `elcl16/remove.gif` and `dlcl16/remove.gif`
- [x] `elcl16/removeall.gif` and `dlcl16/removeall.gif`

Replace by SVG and PNG `elcl16/`
- [x] `mergesessions.gif`
- [x] `export.gif` same as [`eclipse.platform.images/org.eclipse.images/eclipse-svg/org.eclipse.ui/icons/full/etool16/export_wiz.svg`](http://git.eclipse.org/c/platform/eclipse.platform.images.git/tree/org.eclipse.images/eclipse-svg/org.eclipse.ui/icons/full/etool16/export_wiz.svg)
- [x] `import.gif` same as [`eclipse.platform.images/org.eclipse.images/eclipse-svg/org.eclipse.ui/icons/full/etool16/import_wiz.svg`](http://git.eclipse.org/c/platform/eclipse.platform.images.git/tree/org.eclipse.images/eclipse-svg/org.eclipse.ui/icons/full/etool16/import_wiz.svg)
- [x] `relaunch.gif` based on [`eclipse.platform.images/org.eclipse.images/eclipse-svg/org.eclipse.debug.ui/icons/full/elcl16/runlast_co.svg`](http://git.eclipse.org/c/platform/eclipse.platform.images.git/tree/org.eclipse.images/eclipse-svg/org.eclipse.debug.ui/icons/full/elcl16/runlast_co.svg)
- [x] `runcoverage.gif` based on [`eclipse.platform.images/org.eclipse.images/eclipse-svg/org.eclipse.debug.ui/icons/full/elcl16/runlast_co.svg`](http://git.eclipse.org/c/platform/eclipse.platform.images.git/tree/org.eclipse.images/eclipse-svg/org.eclipse.debug.ui/icons/full/elcl16/runlast_co.svg)
- [x] `session.gif` based on [`eclipse.platform.images/org.eclipse.images/eclipse-svg/org.eclipse.debug.ui/icons/full/elcl16/prev_thread_nav.svg`](http://git.eclipse.org/c/platform/eclipse.platform.images.git/tree/org.eclipse.images/eclipse-svg/org.eclipse.debug.ui/icons/full/elcl16/prev_thread_nav.svg)
- [x] `dump.gif` based on `eclipse.platform.images/org.eclipse.images/eclipse-svg/org.eclipse.debug.ui/icons/full/obj16/osprct_obj.svg`
- [x] `showtypes.gif` same as `eclipse.platform.images/org.eclipse.images/eclipse-svg/org.eclipse.jdt.ui/icons/full/eview16/types.svg`
- [x] `showpackages.gif` same as `eclipse.platform.images/org.eclipse.images/eclipse-svg/org.eclipse.jdt.ui/icons/full/obj16/package_obj.svg`
- [x] `showpackageroots.gif` same as `eclipse.platform.images/org.eclipse.images/eclipse-svg/org.eclipse.jdt.ui/icons/full/obj16/packagefolder_obj.svg`
- [x] `showprojects.gif` based on `eclipse.platform.images/org.eclipse.images/eclipse-svg/org.eclipse.jdt.ui/icons/full/eview16/projects.svg`

No need to add SVGs for corresponding `dlcl16/` - PNGs will be generated by `eclipse.platform.images/org.eclipse.images.renderer`.

Replace by SVG and PNG `eview16/`
- [x] `coverage.gif` based on [`eclipse.platform.images/org.eclipse.images/eclipse-svg/org.eclipse.jdt.ui/icons/full/elcl16/clear_co.svg`](http://git.eclipse.org/c/platform/eclipse.platform.images.git/tree/org.eclipse.images/eclipse-svg/org.eclipse.jdt.ui/icons/full/elcl16/clear_co.svg)
- [x] `exec.gif` based on `session.svg` and `coverage.svg`

Replace by SVG and PNG `etool16/`
- [x] `session_import.gif` based on `session.svg`
- [x] `session_export.gif` based on `coverage.svg`
- [x] `java_launch.gif` based on `org.eclipse.images/eclipse-svg/org.eclipse.jdt.ui/icons/full/etool16/java_app.svg`
- [x] `junit_launch.gif` same as `eclipse.platform.images/org.eclipse.images/eclipse-svg/org.eclipse.jdt.junit/icons/full/obj16/julaunch.svg`
- [x] `junitplugin_launch.gif` same as `eclipse.platform.images/org.eclipse.images/eclipse-svg/org.eclipse.pde.ui/icons/obj16/julaunchpgn.svg`

Replace by SVG and PNG `obj16/`
- [x] `session.gif` same as `elcl16/session.svg`
- [x] `markerfull.gif`
- [x] `markerno.gif`
- [x] `markerpartial.gif`

Replace by SVG and PNG `wizban/`
- [x] `run_coverage.gif` based on `eclipse.platform.images/org.eclipse.images/eclipse-svg/org.eclipse.jdt.ui/icons/full/wizban/export_javadoc_wiz.svg` and `eclipse.platform.images/org.eclipse.images/eclipse-svg/org.eclipse.jdt.ui/icons/full/wizban/cleanup_wiz.svg`
- [x] `import_session.gif` based on `run_coverage.svg`
- [x] `export_session.gif` based on `import_session.svg`

To render:
```
mvn org.eclipse.images:org.eclipse.images.renderer:render-icons \
  -Dtycho.mode=maven \
  -Declipse.svg.sourcedirectory=svg \
  -Declipse.svg.createFragments=false \
  -Declipse.svg.scale=2
```

### CODE REVIEW

**Comment by Godin** [comment]
@marchof while this is still work in progress and not ready for a merge (at least requires test on  HiDPI display), I would like to hear your early feedback, especially that my perception of icons biassed since I have some form of red-green color blindness (mainly for color blends, gradients)

**Comment by Godin** [comment]
@marchof I finished here. And did test on a Mac laptop with Retina, however to my taste with previous icons wasn't that bad, but in some places definitely looks better after change.

One commit per icon to simplify comparison in GitHub UI.

So could you please review/validate?

**Comment by Godin** [comment]
@LiamHD since this originally was requested by you in https://github.com/jacoco/eclemma/issues/120 , could you please test too?

**Comment by marchof** [comment]
@Godin Call me deeply impressed! I wasn't aware that we we also have a graphics genius in our team ;-)

Icons as well as PR look good to me!

- Should I squash and merge?
- How do we handle change log? I think this is noteworthy.

**Comment by Godin** [comment]
@marchof nothing special - just quick learning of Inkscape and mostly search and copying from existing Eclipse icons.

So far our changelog - is plain list, so I'll just add a new entry in it and will do squash and merge. If you think about better representation for "noteworthy" - let's do this separately.

**Comment by marchof** [comment]
@Godin Change log is perfect as is. I just wanted to express that this should be added. Thank!

**Pull request merged**
